spring:
  redis:
    sentinel:
      nodes:
        ------:26381,------:26382
      master: mymaster
    timeout: 10000ms
    database: 0
    jedis:
      pool:
        max-active: 50
        max-idle: 50
        max-wait: -1ms
        min-idle: 0

    #    lettuce:
    #      pool:
    #        max-active: 50
    #        max-idle: 50
    #        min-idle: 0
    #        max-wait: -1ms
    password: ------


  #数据库连接配置
  datasource:
    url:
      jdbc:mysql://-------:3306/learning?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&autoReconnect=true&useSSL=false
    username:
      root
    password:
      -------
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    #    hibernate:
    #      ddl-auto: validate
    show-sql: true
server:
  port: 8081