spring:
  redis:
    sentinel:
      nodes:
        -----:26381,----:26382
      master: mymaster
    database: 0
    lettuce:
      pool:
        max-active: 500
        max-idle: 500
        min-idle: 0
        max-wait: -1ms
    password: ----

# 单机模式
#spring:
#  redis:
#    database: 0
#    lettuce:
#      pool:
#        max-active: 500
#        max-idle: 500
#        min-idle: 0
#        max-wait: -1ms
#    host: -------
#    port: 6379
#    password: -----